model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GENAI_API

litellm_settings:
  fallbacks:
    - gpt-4o-mini: ["gemini-2.0-flash"]
    - gemini-2.0-flash: ["gpt-4o-mini"]
  num_retries: 1
  request_timeout: 30

general_settings:
  master_key: os.environ/LITELLM_API_KEY
